Repository mk3058/42_IRC, pull requests merged in 2024-01, with the labels that each got.

#3 CI 설정 추가
  .github/workflows/branch-naming-convention.yml
  .github/workflows/build-test.yml
  .github/workflows/commit-message-convention.yml
  .github/workflows/commitlint.config.js
  .github/workflows/memory-leak-check.yml
  README.md
Labels: ci

#5 PR 병합 후 master 브랜치의 GitHub action이 실패하는 문제 수정
  .github/workflows/branch-naming-convention.yml
  README.md
Labels: ci

#7 프로젝트 변경사항 반영
  .github/workflows/memory-leak-check.yml
  Makefile
  README.md
  main.cpp
Labels: docs

#19 C++11 메서드들을 c++98 표준에 맞도록 수정했습니다.
  StatusCode/StatusCode.cpp
  StatusCode/StatusCode.hpp
  request/Command.cpp
  request/Command.hpp
  request/Parameter.hpp
  request/Prefix.hpp
  request/Request.cpp
Labels: fix

#20 feat: icommand_interface
  .gitignore
  Controller/ICommand.cpp
  Controller/ICommand.hpp
Labels: feat

#28 ChannelMap 클래스 추가
  Channel/ChannelMap.cpp
  Channel/ChannelMap.hpp
Labels: feat

#33 ICommand 클래스 생성자 추가
  Channel/Channel.cpp
  Channel/Channel.hpp
  Controller/ICommand.cpp
  Controller/ICommand.hpp
  User/User.cpp
  User/User.hpp
  request/Request.cpp
  request/Request.hpp
Labels: feat

#35 서버파트에 관한 수도코드를 추가했습니다
  Server/Server.cpp
  Server/Server.hpp
  main.cpp
Labels: feat

#48 error message builder를 static 함수로 수정했습니다
  response/Response.hpp
Labels: fix

#69 서버 객체를 static 으로 저장하던 문제를 수정했습니다
  Controller/Privmsg.cpp
  Controller/Privmsg.hpp
  Controller/Topic.cpp
  Controller/Topic.hpp
Labels: fix
